config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy'


  resources :users, only: [:create, :show] do
    resources :collections, only: [:index, :create, :update, :destroy]
  end

  resources :consoles, only: [:index, :show] do
    resources :games, only: :new
  end

  resources :games, except: :destroy
  post '/users/:user_id/collections/:id' => 'collections#create', as: 'addtocollection'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/console.rb
class Console < ApplicationRecord
  has_many :games
  validates :name, presence: true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :collections
  has_many :users, through: :collections
  belongs_to :console
end

app/models/user.rb
class User < ApplicationRecord
  has_many :collections
  has_many :games, through: :collections
  has_secure_password

  validates :name, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true
  validates :password, presence: true   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def require_login
    redirect_to login_path unless logged_in?
  end  
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
    binding.pry
  end

  def edit
  end

  def update
  end

  private

  def collection_params
    params.require(:collection).permit(:user_id, :game_id, :status, :hours, :review, :rating)
  end

end

app/controllers/consoles_controller.rb
class ConsolesController < ApplicationController

  def index
    @console = Console.all
  end

  def show
    @console = Console.find(params[:id])
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @game = Game.all
  end

  def show
    @game = Game.find(params[:id])
    @user = current_user
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  private

  def game_params
    params.require(:game).permit(:title, :console_id, :genre, :description, :release_year)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    if params[:user][:email].empty? || params[:user][:password].empty?
      redirect_to login_path
    elsif @user && @user.try(:authenticate, params[:user][:password])
      session[:user_id] = @user.id
      redirect_to user_collections_path(@user)
    else
      redirect_to login_path
    end
  end

  def facebook
    @user = User.find_or_create_by(uid: auth['uid']) do |u|
      u.name = auth['info']['name']
      u.email = auth['info']['email']
      u.password = 'password'
    end
    @user.save
    session[:user_id] = @user.id
    redirect_to user_collections_path(@user)
  end



  def destroy
    session.destroy
    redirect_to root_path
  end


  private

  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_collections_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/consoles_helper.rb
module ConsolesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/collections/index.html.erb
<h1>Collections Index</h1>

app/views/consoles/index.html.erb
<h1>Consoles Index</h1>

<% @console.each do |console| %>
    <h3><%= link_to console.name, console_path(console) %></h3>
<% end %>

app/views/consoles/show.html.erb
<h1><%= @console.name %></h1>

<%= render 'games/games_list', games: @console.games %>

app/views/games/_games_list.html.erb
<% games.each do |game| %>
    <h3><%= link_to game.title, game_path(game) %></h3>
<% end %>

app/views/games/edit.html.erb
<h1>Games Edit</h1>

app/views/games/index.html.erb
<h1>Games Index</h1>

<%= render 'games/games_list', games: @game %>

app/views/games/new.html.erb
<h1>Games New</h1>

app/views/games/show.html.erb
<h1><%= @game.title %></h1>
<br>
<br>

<h3>Console: <%= @game.console.name %></h3> <br>
<h3>Genre: <%= @game.genre %> </h3> <br>
<h3>Description: <%= @game.description %></h3> <br>

<button><%= link_to 'Add to Collection', addtocollection_path(@user, @game), method: :post %></button>

app/views/layouts/_header.html.erb
<header>
<% if !logged_in? %>
  <%= link_to("Log In", login_path) %>
  <%= link_to("Sign Up", signup_path) %>
  <%= link_to('Log in with Facebook!', '/auth/facebook') %>
<% else %>
  <%= link_to("My Collection", user_collections_path(current_user)) %>
  <%= link_to("Consoles", consoles_path) %>
  <%= link_to("Games", games_path) %>
  <%= link_to("Users", users_path) %>
  <%= link_to("Log Out", logout_path) %>
<% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoGameCollector</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="navbar">
      <%= render '/layouts/header' %>
    </div>

    <%= yield %>

  </body>
</html>

app/views/users/new.html.erb
<h1>Create an Account</h1>

<%= form_for @user do |f| %>
  <%= f.text_field :name, placeholder: "Username" %><br>
  <%= f.email_field :email, placeholder: "Email" %><br>
  <%= f.password_field :password, placeholder: "Password" %><br>
  <br>
  <%= submit_tag "Sign Up"%>
<% end %>

app/views/users/show.html.erb
<h1>Users Show</h1>

app/views/welcome/home.html.erb
<h1>Welcome to Video Game Collector!</h1>